# Laplace Kernel

In [1]:
import torch
from dmgp.kernels.laplace_kernel import LaplaceProductKernel, LaplaceAdditiveKernel

In [2]:
n = 2 # the size of x1
m = 4 # the size of x2
d = 1 # dimension of x1, x2
x1 = torch.randn(n,d)
x2 = torch.randn(m,d)
lengthscale = torch.randn(d)
print(x1)
print(x2)

tensor([[-0.5641],
        [-0.1584]])
tensor([[-1.4052],
        [ 0.3557],
        [-0.1865],
        [-0.0255]])


In [3]:
kernel = LaplaceProductKernel(lengthscale=1.)
kernel(x1=x1,x2=x2)

tensor([[0.4312, 0.3986, 0.6856, 0.5836],
        [0.2874, 0.5980, 0.9722, 0.8756]])

In [4]:
x1 = torch.randn(3,10,2)
x2 = torch.randn(6,2)
lengthscale = torch.randn(2)
kernel = LaplaceProductKernel(lengthscale=1.)
kernel(x1=x1,x2=x2).shape

torch.Size([3, 10, 6])